version: '3'
services:
  orientation_server:
    container_name: orientation_server
    build: .
    ports: 
      - '${API_LOCAL_PORT}:${PORT}'
    restart: on-failure
    depends_on:
      - orientation_db
      - orientation_redis

  orientation_db:
    container_name: orientation_db
    image: mysql:8.0
    volumes:
      - ./orientation_db_volume:/var/lib/mysql
    restart: always
    env_file:
      - ./.docker.env

  orientation_pma:
    container_name: orientation_pma
    image: phpmyadmin
    restart: always
    env_file:
      - ./.docker.env
    ports:
      - '${PMA_LOCAL_PORT}:80'
    depends_on:
      - orientation_db

  orientation_redis:
    container_name: orientation_redis
    image: redis
    restart: always
    volumes:
      - ./orientation_redis_volume:/data
