name: Miagrate and Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    sevices:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: utopia
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-retries=3 --health-timeout=5s

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: go version
        run: go version

      - name: Setup MySQL
        run: |
          sudo apt update
          sudo apt install -y default-mysql-client
          mysql -h 0.0.0.0 --port 3306 -u root -p password -e 'CREATE DATABASE IF NOT EXIST utopia;'

      - name: Setup env file
        run: cp .sample.env .env

      - name: Run Migrations
        run: |
          go get -tags 'mysql'  -u github.com/golang-migrate/migrate/v4/cmd/migrate/
          migrate -path "./migrations" -database "mysql://root:password@/utopia" up

      - name: Go Build
        run: go build
